version: '3.9'

services:
  quoted-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: quoted-app
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/quoted-db
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      SPRING_PROFILES_ACTIVE: prod
  mongodb:
    image: mongo:6
    container_name: mongo
    restart: always
    command: mongod --quiet
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
volumes:
  mongo_data:
