spring:
  application:
    name: quoted
  security:
    user:
      name: admin
      password: passwd
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI}
logging:
  level:
    org.mongodb.driver: ERROR
server:
  port: 8080