name: Build and push Docker Image

on:
  push:
    branches:
      - "master"
      
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Allow build.sh to run
        run: chmod +x ./build.sh

      - name: Execute build.sh
        run: ./build.sh
        
      - name: Docker Hub Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: docker build -t ohiagosouza/quoted-app:latest .

      - name: Push Image
        run: docker push ohiagosouza/quoted-app:latest
